DDDEastMidlandsLimited/dddem-web

.travis.yml

As we have chosen travis as our build tool, might as well try integrate it.

Enhancement: Add Travis yml

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/contributing.md
.travis.yml
CODE_OF_CONDUCT.md
README.MD
pull_request_template.md

- Add's github open source documentation (contributing guidelines, code of conduct and issue templates)
- Add brand guide to readme

Enhancement: OSS docs

---

components/Footer.js

All links to open in new tabs
Footer links now open in new tabs
Can follow our social media without repetitively returning to the site
N/A

Ensure footer links open in new tab

---

components/Head.js
static/favicon/manifest.json

Fix for manifest paths and Head paths

---

.travis.yml
aws_deploy

Add delete flag to S3 sync in deployment.
Removes old folders cluttering up s3

Delete redundant directories when deploying

---

.travis.yml

Removes cleanup of artefacts by travis before deploy step to avoid deployment failure.
Application can actually be deployed.

fix path for s3 sync on deploy

---

components/Navigation.js

Add a link on Navigation to the DDD East Midlands Medium page
https://medium.com/dddeastmidlands 
Added a link to Nav. 
Unsure about user experience for a tab that goes to a new page. Should it open in the same tab or a new tab?

add blog tab

---

components/ExternalLink.js
components/Footer.js
components/Navigation.js

External link component added with tracking and fixes footer target link errors

---

components/Company.js
components/ExternalLink.js
components/Navigation.js
data/gold.js
pages/index.js

* To add a link to the logo
* To ensure GA works for those logos
I can't make these links work!
For tracking click-throughs for sponsors

Enhancement: Add external link to Logo

---

pages/faq.js

* Add accessibility questions to FAQ
Add the accessibility questions I have (or nearly have) answers to
Improve the number of people who feel informed and welcome at the event

Enhancement: Add Accessibility Questions

---

data/extraopportunities.js
data/sponsors.js

Update sponsorship page

---

pages/faq.js

Add more questions and answers to accessibility section

---

data/bronze.js

* Add First Response description to Notable Companies

Enhancement: Add First Response description

---

data/sponsors.js

* Add sold out logo to website
nter any applicable Issues here -->

Enhancement: Silver sold out

---

components/Layout.js

fixed side scrollbar

---

pages/about.js

Enhancement: Add video to about page

---

pages/information/speaker-information.js

*  To add a page with all the essential information a speaker might need about DDD East Midlands
npm run dev
Should launch on localhost:3000
ac

Enhancement: Add Information to Speaker Information Page

---

pages/information/speaker-information.js

* Update vote information
* Update PAT testing information

Enhancement: Speaker page voting and PAT testing

---

pages/information/sponsor-information.js

Enhancement: Add on the day information

---

components/Navigation.js
pages/about/crew-information.js

Adds crew information for our volunteers

Enhancement: Add crew information page

---

package-lock.json
pages/about/speaker-information.js

Add information about presentation hardware and software

Fix: Add information about presentation software

---

pages/information/main-page.js

Fixes the button hover bug on the information page. I couldn't actually get to the bottom of why opacity was being treated differently on containers that were in a two-column layout but applying the opacity to contents of the divs inside the container seems to have done the trick.
I also took the opportunity to reduce some repetition in the styles where possible to make maintaining the page easier. I'm mainly back end focused so apologies in advance if there are any React or CSS conventions broken here 😅 
The information page buttons now behave in the same manner when in two-column view and (hopefully) the CSS is easier to maintain.
Fixes #118

Fixes #118 - Hover bug

---

components/Layout.js
components/Navigation.js
pages/index.js

- Add link to Sessionize on the nev
- Add focus on Submissions being open on the homepage

Enhancement: Open submissions

---

data/dates.js

- Correct the date for voting closes

Fix: Change voting closes date

---

components/home/ImportantDate.js
data/dates.js

* Make it obvious when dates have passed
Current Date:
Past Date:

Enhancement: Date Clarity

---

pages/information/main-page.js

* Reorder buttons so the most relevant ones are at the top

Enhancement: Reorder Info Buttons

---

.github/ISSUE_TEMPLATE/hacktober_bug_report.md
.github/ISSUE_TEMPLATE/hacktober_feature_request.md

* Template names need to be unique
* Added hacktober to the titles of hacktober issue templates
N/A
N/A

Fix titles of templates to be unique

---

.github/workflows/main.yml

* Only deploy one version of the site on merge to master

Fix: Ensure only one version built

---

.github/workflows/main.yml

* Enable deployments through GitHub actions
* Update GitHub Actions Deployment scripts
- Keeps CI and CD all in one place
N/A

Migrate: Move Travis commands to GitHub actions

---

pages/2020/hacktober.js

I have added my review in the hacktober page as I was allowed to do by @wordshaker in #181. While merging please label hacktober-accepted when accepting my pull request. This ensures that the pull request is a valid one and it counts.

Added one review to the Hacktober page

---

components/Footer.js
pages/2020/hacktober.js

**Issue solved**
Now the footer is responsive on small screen devices. Kindly merge my pull request with hacktoberfest-accepted label. Thankyou.

Footer issue fixed. Responsive on small screen devices now.

---

components/Footer.js

Make footer responsive on small devices
- Changed footer ul styles flex-flow:row; to flex-flow:column;
- Added media query to keep flex-flow:row on large devices
The website will look good on small devices
N/A

Fix footer links on small devices

---

components/Layout.js
components/PerformanceAnalytics.js
package-lock.json
package.json

Adds Perfume.js to the site to allow tracking of various metrics over time.
Gives us all the performance metrics in GA
Closes #48

Added perfume.js to track performance to GA

---

pages/2020/hacktober.js

* Add my opinion of the East Midlands tech community on the hacktoberfest page.
* I have tested the page after the changes I have made and It all seems to work correctly.
* I could contribute to the opinions shown in the hacktoberfest page. 
This pull request follows the rules on issue #181.

Add one review to the hacktoberfest page (#181)

---

.gitignore
out/.gitignore
out/README.md

Adds an empty directory to git to prevent local build errors regarding permissions.
Reduces confusion for new contributors to the repository.

Adds empty out directory for sitemap

---

components/Head.js
public/robots.txt

Issue's link https://github.com/DDDEastMidlandsLimited/dddem-web/issues/215
Fixes in order to improve SEO (at least 90):
**Content best practices**
**Crawling and indexing**
How to test :
Open the site in Chrome
Open developer tools
Go to the Lighthouse tab in the dev tools
Run and you should see score at 90

Feature Request: Improve Lighthouse SEO Score #215

---

components/companies/CompanyLogoGrid.js
components/companies/GoldCompaniesProvider.js
components/companies/GoldSponsorLogos.js
pages/index.js

- Gold Sponsor logos added to the homepage with hyperlinks
Add the Gold Sponsors to the homepage
N/A
N/A

Add Gold Sponsors back to homepage

---

next.config.js

Fixes issue with next config not being found due to plugins configuration
Pages are visible again
None

Fix for misconfigured next.config.js

---

.github/workflows/codeql-analysis.yml

Remove erroring line from CodeQL
Remove erroring line from CodeQL
Removes error
#287

Fix: Remove checkout head 2 on CodeQL

---

data/dates.js
pages/information/ticket-information.js

- Push dates back a week 
Push dates back a week to give us room to get organised
The team need more time
N/A

Fix: Push dates back a week on index page

---

components/Navigation.js
components/Navigation.test.js

- Remove link for talk submission
- Add link to tickets
- Remove link for talk submission
- Add link to tickets
Relevant links in Nav
N/A

Update navigation bar to include Tickets and not Submit a Talk

---

components/Navigation.js
components/Navigation.test.js
data/talks/talks.js
package-lock.json
pages/talks.js

adds data, nav bar element and minor copy fix for the 2021 talks page

Add Talks page for 2021

---

data/talks/talks.js

- Correct grammar in one talk
Makes speaker happy
N/A

Correct grammar in one talk

---

components/Navigation.js

Fixes #376 
Build passes properly
#376

Remove unneeded event param

---

pages/information/attendee-information.js
pages/information/main-page.js
pages/information/speaker-information.js

- Update the links on the Information Page
- Add vaccination expectations
The information our attendees and sponsors will be looking for will have changed. Updates what is available.
N/A
N/A

Enhancement: Update Information main page

---

pages/2021/speakers/speakergrid.js

- Add Manu as a confirmed speaker
Manu added to speakers page and her personal page added
People can find out more about her
N/A

Enhancement: Add Manu to speakers page

---

components/companies/CompaniesProvider.js
components/companies/CompanyGrid.js
components/companies/PartnerCompaniesProvider.js
components/companies/PartnerSponsorLogos.js
pages/2021/notable-companies.js

- Seperate sponsors with descriptions to those without and make the top ones larger
Size and position of logo depending on how much sponsor is paying
N/A
N/A

Fix: Two layers on notable companies

---

pages/2021/speakers/jennifer-mackown.js
pages/2021/speakers/speakergrid.js

Add Jennifer to the speakers page
Another confirmed speaker added
People can find out more about our speakers
N/A

Enhancement: Add Jen

---

pages/2021/speakers/jennifer-mackown.js
pages/2021/speakers/steve-collins.js
pages/2021/speakers/tania-allard.js

- Change Steves Talk
- Update Jens talk to be 15 mins instead of 60 mins
Give correct details
N/A

Fix: Edit Speaker Details

---

pages/2021/speakers/speakergrid.js

- shortest talks last in order

Fix: re-order speakers

---

data/dates.js
pages/information/attendee-information.js
pages/information/crew-information.js
pages/information/speaker-information.js
pages/information/sponsor-information.js
pages/talks.js

- Make sure times and dates are correct on the website
So people aren't misinformed
N/A

Fix: Edit times mentioned on pages

---

pages/2021/speakers/tania-allard.js

- Add Tanias Keynote description
So people can get excited for this awesome talk!!
N/A

Enhancement: Add Tanias Keynote description

---

pages/information/attendee-information.js

- Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
- All new code requires tests to ensure against regressions
small typo fixes
better text
n/a

fix small typo

---

pages/information/conference-information.js

- Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
- All new code requires tests to ensure against regressions
small typo fix
better text
n/a

small typo fix

---

pages/pastconferences/pastspeakers/2021/clifford-agius.js
pages/pastconferences/pastspeakers/2021/connell-w.js
pages/pastconferences/pastspeakers/2021/dylan-beattie.js
pages/pastconferences/pastspeakers/2021/james-croft.js
pages/pastconferences/pastspeakers/2021/jennifer-mackown.js
pages/pastconferences/pastspeakers/2021/kojo-hinson.js
pages/pastconferences/pastspeakers/2021/leke-sholuade.js
pages/pastconferences/pastspeakers/2021/lex-lofthouse.js
pages/pastconferences/pastspeakers/2021/manu-magalhaes.js
pages/pastconferences/pastspeakers/2021/matt-whetton.js
pages/pastconferences/pastspeakers/2021/poornima-nayar.js
pages/pastconferences/pastspeakers/2021/riz-akmal-khan.js
pages/pastconferences/pastspeakers/2021/ryan-yates.js
pages/pastconferences/pastspeakers/2021/simon-painter.js
pages/pastconferences/pastspeakers/2021/stephen-haunts.js
pages/pastconferences/pastspeakers/2021/stephen-jackson.js
pages/pastconferences/pastspeakers/2021/steve-collins.js
pages/pastconferences/pastspeakers/2021/tania-allard.js
pages/pastconferences/pastspeakers/2021/tom-morton.js

- Back to speakers page goes to the right page
Changed the button type
Ease of use
N/A

Fix: Repair Past Speakers Links on Speakers Pages

---

package-lock.json

Run npm audit fix
Security benefits
N/A

Fix: Run npm audit fix

---

pages/pastconferences/album.js

Add the photos from 2021
N/A
N/A

Enhancement: Add 2021 Photos

---

next.config.js
package-lock.json
package.json
utils/generateSiteMap.js

Fix next config issue
Upgrade perfume.js
Issue was the next.config file being ignored and therefore not writing out urls or folder structure correctly.
Have adapted the file to support modern syntax.
Site Works!

Fix next config issue

---

package-lock.json
package.json

Upgrade postcss
Upgrade out out of date packages
Fixes security fix
Fixes Security flaw in post css
N/A

Fix: Upgrade packages

---

components/Footer.js

- Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
- All new code requires tests to ensure against regressions
Adds our Mastodon link to the footer. Includes "me" in the rel attribute to allow verification on Mastodon
new social media site
None

Add Mastodon

---

components/GoogleAnalytics.js
data/dates.js

- Change dates on website to be more accurate
- Change dates on website to be more accurate
- Add browser check to see if it fixes the nextjs error about window
NA
NA

Change homepage dates and Try add browser check to GA

---

components/Footer.js
components/Navigation.js
components/Navigation.test.js
pages/index.js

- Add `Apply To Speak` to the nav that links out to sessionize
- Move YouTube to Footer.
CAn reach sessionize from the website
N/A

Enhancement: Add Apply to Speak to Nav

---

components/content/SocialMedia.js
pages/contact.js
pages/guides/crew.js
pages/index.js
styles/base.scss
styles/components/_index.scss
styles/main.scss

- Change hashtag
- Add apply button to homepage
N/A
N/A

Fix: Remove reference to 2021

---

data/dates.js

Update date to reflect later release of tickets
More accurate information for the attendees
N/A

Fix dates on homepage

---

components/Navigation.js
components/TicketButton.js
data/sponsors/gold.js
pages/index.js
pages/information/ticket-information.js

Add links to navigation and home page to Eventbrite for tickets
Easier to find where to get tickets
N/A

Enhancement: Ticket links

---

data/dates.js

Add past to date for speaker submission closing
Accurate data on website
N/A

Fix: Put speaker submission closing in the past

---

data/sponsors/gold.js

Enhancement: Add BJSS description

---

pages/sponsor/sponsor-the-event.js

Remove broken button from sponsor me page
Enables people to contact Rachel 
N/A

Fix: Change Rachels details on sponsor page

---

components/Head.js
components/Navigation.js
data/dates.js
pages/agenda.js
public/static/client/sessionize.js

- Add Agenda page with Sessionize embed
- Add Agenda tab to navigation
Shares the awesome agenda
N/A

Enhancement: Add Agenda to Website

---

pages/sponsor/sponsorship-tiers.js

Change booth to Silver as part of re-brand
N/A
N/A

Change booth to silver

---

pages/sponsor/sponsor-the-event.js
pages/sponsor/sponsorship-tiers.js

Just some broken links.
Sorry about the branch name!

Fix some broken links between the sponsorship pages

---

pages/2021/hacktober.js
pages/information/event-activities.js

Remove Microsoft Clous Skills
N/A
N/A
N/A

Fix: Edit event activities page

---

components/Navigation.js
pages/index.js
yarn.lock

- Update homepage
- Update navigation
- Accurate information
N/A

Update homepage and navigation bar

---

.github/workflows/publish_to_s3_job.yml
.github/workflows/publish_unit_tests.yml
.github/workflows/test_job.yml

Upgrade actions/upload-artifact
